name: Solar System wf

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superDate'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:    
    unit-testing:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4      
        - name: Setup NodeJS v18
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: install dependencies
          run: npm install
        - name: Run unit-test
          run: echo "npm test"   > test_result.txt
        - name: Upload 2.txt file
          uses: actions/upload-artifact@v3
          with:
            name: test_result.txt upload
            path: test_result.txt
  

